packages:
  - backend
  - e2e-tests
  - geo-resolver
  - frontend

onlyBuiltDependencies:
  - '@apollo/protobufjs'
  - '@nestjs/core'
  - '@prisma/client'
  - '@prisma/engines'
  - esbuild
  - prisma
